CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectid integer REFERENCES projects(id)
);

INSERT 
INTO projects(name, priority, description, deliverydate)
VALUES('Make a web app', 1, 'Usando JS', '2020-05-12');

INSERT 
INTO projects(name, priority, description, deliverydate)
VALUES('Fix bugs', 1, 'Usando JAVA', '2020-05-13');

INSERT 
INTO projects(name, priority, description, deliverydate)
VALUES('Desktop app', 2, 'Usando C++', '2020-05-14');

INSERT 
INTO tasks(name, done, projectid)
VALUES('Download ReactJS', false, 1);

INSERT 
INTO tasks(name, done, projectid)
VALUES('Download Node', false, 1);

INSERT 
INTO tasks(name, done, projectid)
VALUES('Setup project', false, 1);

